package com.github.nill14.utils.exception;

public class StackTraceTest {
	public static void main(String[] args) {
		System.out.println(Dummy.call(1));
	}
}
